#So in Spring Boot 2.4 we’re planning to make two significant changes to the way the properties and YAML files are loaded:
#
#    Documents will be loaded in the order that they’re defined.
#
#    Profiles can no longer be activated from profile specific documents.
spring:
    application:
        name: user-service
    config:
        name: dev-YAML
        activate:
            on-profile: local
    datasource:
        name: someName
        url:
            - www.heb.local.com
            - www.heb.local.com
debug: true
---
spring:
    config:
        activate:
            on-profile: UAT
        name: uat-YAML
    datasource:
        name: someName
        url:
            - www.heb.local.com
            - www.heb.local.com
---
spring:
    config:
        activate:
            on-profile: Prod
        name: prod-YAML
    datasource:
        name: someName
        url:
            - www.heb.local.com
            - www.heb.local.com