#So in Spring Boot 2.4 we’re planning to make two significant changes to the way the properties and YAML files are loaded:
#
#    Documents will be loaded in the order that they’re defined.
#
#    Profiles can no longer be activated from profile specific documents.

# Defualt Settings
spring:
    application:
        name: user-service
    config:
        name: dev-YAML
        activate:
            on-profile: local
    datasource:
        name: localH2
        url:
            - www.heb.local.com
            - www.heb.local.com
debug: true
--- #Must pass in Var to overwrite defult
spring:
    config:
        activate:
            on-profile: UAT
        name: uat-YAML
    datasource:
        name: uatDB
        url:
            - www.heb.uat.com
            - www.heb.uat.com
debug: true
--- # Will overwrite previous two set ups when correct var is passed in
spring:
    config:
        activate:
            on-profile: Prod
        name: prod-YAML
    datasource:
        name: prodDB
        url:
            - www.heb.prod.com
            - www.heb.prod.com