spring:
    config:
        activate:
            on-profile: dev
name: dev-YAML
environment: local
enabled: false
servers: 
    - www.abc.test.com
    - www.xyz.test.com
---
spring:
    config:
        activate:
            on-profile: test
name: test-YAML
environment: testing
enabled: false
servers: 
    - www.abc.test.com
    - www.xyz.test.com
