spring:
    config:
        activate:
            on-profile: local
name: devYAML
environment: local
enabled: false
servers: 
    - www.heb.local.com
    - www.heb.local.com
debug: true
---
spring:
    config:
        activate:
            on-profile: UAT
name: uat-YAML
environment: testing
enabled: false
servers: 
    - www.abc.uat.com
    - www.xyz.uat.com
---
spring:
    config:
        activate:
            on-profile: Prod
name: prod-YAML
environment: production
enabled: false
servers:
    - www.abc.prod.com
    - www.xyz.prod.com